---
driver:
  name: dokken
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-trusty
    driver:
      image: ubuntu:trusty

suites:
  - name: default
    run_list:
      - recipe[example-chef-project::default]
    attributes:
